"""add complaints role, mentor application fields, complaints table

Revision ID: 726608ca66cf
Revises: cfff80f6347e
Create Date: 2026-07-14 22:50:18.489291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726608ca66cf'
down_revision = 'cfff80f6347e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('qualification_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('personal_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interview_scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('interview_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.drop_column('interview_status')
        batch_op.drop_column('interview_scheduled_at')
        batch_op.drop_column('personal_statement')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('qualification_level')
        batch_op.drop_column('university')

    # ### end Alembic commands ###
